buildscript {
    repositories {
    	mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.4'
    }
}

plugins {
    id 'io.franzbecker.gradle-lombok' version '1.8' apply false
}

allprojects {
    repositories {
    	mavenLocal()
        mavenCentral()
        jcenter()
    }

    group = "be.zeldown.joid"
    version = "6.5.4"
}

ext {
    lwjglVersion = "3.3.4"
    lwjglNatives = org.gradle.internal.os.OperatingSystem.current().isWindows() ? "natives-windows" : org.gradle.internal.os.OperatingSystem.current().isMacOsX() ? (System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos") : "natives-linux"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.franzbecker.gradle-lombok'

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    compileJava {
        options.encoding = 'UTF-8'
    }

    dependencies {
        compile "org.projectlombok:lombok:1.18.34"
    }
}

/* Scripts */
task installLocalGitHook(type: Copy){
	from new File(rootProject.rootDir, 'scripts/pre-push')
	into new File(rootProject.rootDir, '.git/hooks')
	
	fileMode 0775
}
