rootProject.name = 'JOID'

include 'core'
include 'base-glfw', 'base-openal', 'base-opengl'
include 'backend-lwjgl2', 'backend-lwjgl3', 'backend-vulkan'
include 'tool-msdf', 'tool-testkit'
include 'sample-showcase'

rootProject.children.each { module ->
    module.projectDir = file(module.name.replaceFirst('-', '/'))
}
