apply plugin: 'com.github.johnrengelman.shadow'

archivesBaseName = "joid-lwjgl2"

dependencies {
    compile project(':core')

    compile "org.lwjgl.lwjgl:lwjgl:2.9.1"
}

apply from: rootProject.file('gradle/backend.gradle')

/* Demo */
task runDemo(type: JavaExec) {
    group = 'JOID'
    description = 'Launches the LWJGL 2 demo window.'
    main = "be.zeldown.joid.impl.lwjgl2.demo.DemoWindow"
    classpath = sourceSets.main.runtimeClasspath
    jvmArgs "-Djava.library.path=${file('native').absolutePath}"
}


test {
    jvmArgs "-Djava.library.path=${file('native').absolutePath}"
}