name: Update Version

on:
  release:
    types:
      - created

jobs:
  update-files:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Get the tag name
      id: set-tag
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0)
        TAG_NAME=${TAG_NAME//[-]/ }
        TAG_NAME=${TAG_NAME:1}
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

        COMMIT_SHA=$(git rev-parse HEAD)
        COMMIT_SHA=${COMMIT_SHA:0:7}
        echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
    - name: Update version in files
      run: |
        sed -i "s/project.version = \".*\"/project.version = \"${TAG_NAME}\"/g" build.gradle
        sed -i "s/version-\([^[:space:]-]*\) \([^[:space:]-]*\)-/version-${TAG_NAME} (${COMMIT_SHA})-/g" README.md
        git add README.md
        git add build.gradle
        git commit -m "update: update version to ${TAG_NAME} (:bookmark:)"
        git push origin HEAD:main